
[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "RobotoMono Nerd Font"

[scrolling]
history = 10000

[window]
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Alacritty"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
